export const classImages = [
    {name: "Barbarian",
    image: "./placeholder-image.jpg"},
    {name: "Bard",
    image: "./placeholder-image.jpg"},
    {name: "Cleric",
    image: "./placeholder-image.jpg"},
    {name: "Druid",
    image: "./placeholder-image.jpg"},
    {name: "Fighter",
    image: "./placeholder-image.jpg"},
    {name: "Monk",
     image: "./placeholder-image.jpg"},
    {name: "Paladin",
    image: "./placeholder-image.jpg"},
    {name: "Ranger",
    image: "./placeholder-image.jpg"},
    {name: "Rogue",
    image: "./placeholder-image.jpg"},
    {name: "Sorcerer",
    image: "./placeholder-image.jpg"},
    {name: "Warlock",
    image: "./placeholder-image.jpg"},
    {name: "Wizard",
    image: "./placeholder-image.jpg"}
]